### ISSUE TITLE
bad path prefix on alter1, 2, 3 in upgrade guide

### ISSUE THREAD

**Issue by taur** [shupp/VegaDNS-API#7]
files are not located in root, missing sql/ path prefix
`mysql -u vegadns -p -h localhost vegadns < sql/new_tables_only.sql`
`mysql -u vegadns -p -h localhost vegadns < alter-01.sql`
`mysql -u vegadns -p -h localhost vegadns < alter-02.sql`
`mysql -u vegadns -p -h localhost vegadns < alter-03.sql`
`mysql -u vegadns -p -h localhost vegadns < sql/data_api_keys_only.sql`
should be:
`mysql -u vegadns -p -h localhost vegadns < sql/new_tables_only.sql`
`mysql -u vegadns -p -h localhost vegadns < sql/alter-01.sql`
`mysql -u vegadns -p -h localhost vegadns < sql/alter-02.sql`
`mysql -u vegadns -p -h localhost vegadns < sql/alter-03.sql`
`mysql -u vegadns -p -h localhost vegadns < sql/data_api_keys_only.sql`

**Comment by shupp** [comment]
Fixed, thanks!
