### ISSUE TITLE
ENV variables

### ISSUE THREAD

**Issue by BobTB** [shupp/VegaDNS-API#8]
Hi, I am using VEGADNS now for more than 10 years :) Found your api/ui docker image, which I managed to run, but where can I get the list of ENV variables I can use? I need to setup mysql and stuff and import my old database from 13.3 somehow.

**Comment by BobTB** [comment]
I found some in https://github.com/shupp/VegaDNS-API/blob/master/seed_mysql_data.sh 

Will try to get it up and running.

**Comment by BobTB** [comment]
Hm.. it wants

DB_CA_FILE env variable undefined, skipping MySQL SSL config.
SECRET_DB_CA_CERT env variable undefined, skipping MySQL SSL config.

Ugh... certificate and stuff?

**Comment by shupp** [comment]
You can see an example of all possible environment variables in the python config.py script called from docker:

https://github.com/shupp/VegaDNS-API/blob/master/docker/templates/config.py

DB_CA_FILE and SECRET_DB_CA_CERT are optional.  Those are just warnings that it's being skipped.

**Comment by BobTB** [comment]
Oh, thank you for fast reply!
